// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vxlxifktgoazfgtilgyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4bHhpZmt0Z29hemZndGlsZ3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3MzI3NTcsImV4cCI6MjA5NjMwODc1N30.tu4B4YK4mnAtiZxOopyVO5qf_uzifsASvWSChF54Vjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);